apiVersion: apps/v1 #version of the Kubernetes API you're using to create this object
kind: Deployment  #What kind of object you want to create
metadata: #Data that helps uniquely identify the object
   name: empms

spec: #What state you desire for the object
  selector:
    matchLabels:
      app: empms


  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: empms
    spec:   #What state you desire for the object

      containers:
      - name: empms #container name
        image: 'farheenkhan141/empms-spring' #image name
        ports:
        - containerPort: 8084 # greeting server runs on port 8084
